# Generated by Django 6.1 on 2026-08-25 14:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "saldo",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limite_semanal",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "umbral_alerta",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        help_text="Porcentaje de consumo para disparar la alerta (ej. 80.00)",
                        max_digits=5,
                    ),
                ),
                (
                    "cuenta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tope",
                        to="finanzas.cuenta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ingreso", "Ingreso"),
                            ("gasto", "Gasto"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("creada_por_ia", models.BooleanField(default=False)),
                (
                    "cuenta_destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones_destino",
                        to="finanzas.cuenta",
                    ),
                ),
                (
                    "cuenta_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transacciones_origen",
                        to="finanzas.cuenta",
                    ),
                ),
            ],
        ),
    ]
