# Generated by Django 6.1 on 2026-08-25 14:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tope",
            name="umbral_alerta",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("80.00"),
                help_text="Porcentaje de consumo para disparar la alerta (ej. 80.00)",
                max_digits=15,
            ),
        ),
    ]
