# Generated by Django 6.1.1 on 2026-09-23 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Ahorros", "Cuenta de Ahorros"),
                            ("Corriente", "Cuenta Corriente"),
                            ("Billetera Digital", "Billetera Digital"),
                            ("Tarjeta de Crédito", "Tarjeta de Crédito"),
                        ],
                        default="Ahorros",
                        max_length=30,
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tope_gasto_mensual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuentas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("servicio_preset", models.CharField(default="otro", max_length=50)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[("Mensual", "Mensual"), ("Anual", "Anual")],
                        default="Mensual",
                        max_length=20,
                    ),
                ),
                ("fecha_proximo_pago", models.DateField()),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="app.cuentabancaria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
