# Generated by Django 6.1.1 on 2026-09-24 01:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaAhorro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "monto_objetivo",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monto_actual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("fecha_limite", models.DateField(blank=True, null=True)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas_ahorro",
                        to="app.cuentabancaria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas_ahorro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
