# Generated by Django 6.1.1 on 2026-09-23 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ingreso", "Ingreso"),
                            ("gasto", "Gasto"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to="app.cuentabancaria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
